### ISSUE TITLE
ID to key mapping in compute plan

### ISSUE THREAD

**Issue by jmorel** [Substra/substra-chaincode#104]
Following #102, the ID to key mapping is only returned after a create or an update and only contains the newly created keys.

From the end user standpoint, this could be an issue: let's say there is a connexion interruption or that their script failed right after the create/update : the mapping is lost forever and they have no way to add more tuples to the compute plan.

Adding the id_to_key mapping as an independent value increased the size of the CP object threefold. We could however replace the `*tuple_keys` by `*tuple_id_to_keys` and only increase it twofold. This is of course a significant increase but we wouldn't be breaking our only recovery strategy (get the object to know where you're at).

**Comment by samlesu** [comment]
As pointed by @jmorel, in case of a timeout the add response from the chaincode may be lost. 

That's the reason why I think we must ensure the get / add responses are the same.
