### ISSUE TITLE
Purpose of Permission.include

### ISSUE THREAD

**Issue by GuillaumeCisco** [Substra/substra-chaincode#18]
What is the goal of the `include` method of the `Permission` struct?

I can see its declaration here:
https://github.com/SubstraFoundation/substra-chaincode/blob/dev/chaincode/permissions.go#L114
and it is tested here:
https://github.com/SubstraFoundation/substra-chaincode/blob/dev/chaincode/permissions_test.go#L81

But I cannot find any other references to this method elsewhere in the project.
What is its purpose?

Thank you,

**Comment by Kelvin-M** [comment]
The function `include` is used to test different permissions inclusion as you can see in this https://github.com/SubstraFoundation/substra-chaincode/blob/dev/chaincode/permissions_test.go#L60-L84

This was implemented as users may want to use it to validate download or process permissions, but currently it's not used in substra-chaincode as permissions are validated directly in substra-backend.
