### ISSUE TITLE
[BUG] Invalid JSON tag in permission

### ISSUE THREAD

**Issue by thibaultrobert** [Substra/substra-chaincode#29]
**Describe the bug**
The `omitempty` empty tag in [permission.go](https://github.com/SubstraFoundation/substra-chaincode/blob/30fa50c5780c2957f8cf47effb3e720fba1e7a39/chaincode/permissions.go#L38) is invalid. It should be as follow:
```go
AuthorizedIDs []string `json:"authorizedIDs,omitempty"`
```
The problem here is that this update breaks the tests in a non explicit way. So they should be fixed so they validate this behavior.

**To Reproduce**
1. Change the JSON tag in question to the suggested version
2. Run all the tests (`go test ./..`in the `chaincode` directory)
3. See it failed

**Expected behavior**
All test should pass with the `omitempty` tag correctly set.

**Additional context**
This issue was created following the PR #14

**Comment by Kelvin-M** [comment]
Fixed by https://github.com/SubstraFoundation/substra-chaincode/pull/89
