### ISSUE TITLE
Add more elements to compute the Objective unique key

### ISSUE THREAD

**Issue by samlesu** [Substra/substra-chaincode#33]
Currently the key is computed from the description hash. It is used to ensure multiple objectives could use the same metrics.

When modifying the metrics script to fix a bug for instance, the objective key is still same. It can be confusing to force the user to update the description in order to create a new objective.

What about adding the metrics hash as well?

**Comment by Kelvin-M** [comment]
Keys are now random and provided by the user, this should not be an issue anymore :)
