### ISSUE TITLE
[BUG] createComputePlan and queryComputePlan(s) have different outputs

### ISSUE THREAD

**Issue by jmorel** [Substra/substra-chaincode#36]
**Describe the bug**
Use `createComputePlan` and you'll get an `outputComputePlan` while the `queryComputePlan` and `queryComputePlans` method return `outputComputePlanDetails`

This means that the former one doesn't include the `algoKey` and `objectiveKey` while the latter ones use `traintuples`/`testtuples` instead of `traintupleKeys`/`testtupleKeys`.

**Expected behavior**

They should return the same data in the same format.

This common format could be a mix of the two structs with the attributes:
* `computePlanID`
* `algoKey`
* `objectiveKey`
* `traintupleKeys`
* `testtupleKeys`

I offer to use traintupleKeys and testtupleKeys because we don't include the full traintuples and testtuples in the compute plan.

Also, when the testtupleKeys is empty, an empty list should be returned (instead of `null`)

**Comment by AurelienGasser** [comment]
Since we want to support compute plans with multiple algos, should `algoKey` be removed from the output?

**Comment by jmorel** [comment]
Yes, absolutely!
