### ISSUE TITLE
[BUG] Reject compute plans with duplicated tuple definitions

### ISSUE THREAD

**Issue by jmorel** [Substra/substra-chaincode#66]
**Describe the bug**
Currently you can create a compute plan with multiple times the same tuple declaration and it will be accepted : only one tuple will be created for all of these definitions.

This creates an issue with complex, generated compute plans: a simple typo can lead to accidently duplicating the tuples and leaving you wondering why half of the declared tuples disappeared.

I think we should reject the creation of such compute plans, with an error saying that there are duplicate definitions.

**To Reproduce**

Create a compute plan with twice the same traintuple, with just a different traintuple id.

For example, using our e2e test framework:

```python
def test_bad_compute_plan(factory, session):
    spec = factory.create_algo()
    algo = session.add_algo(spec)

    spec = factory.create_dataset()
    dataset = session.add_dataset(spec)

    spec = factory.create_data_sample(test_only=False, datasets=[dataset])
    data_sample = session.add_data_sample(spec)

    cp_spec = factory.create_compute_plan()
    cp_spec.add_traintuple(
        algo=algo,
        dataset=dataset,
        data_samples=[data_sample]
    )
    cp_spec.add_traintuple(
        algo=algo,
        dataset=dataset,
        data_samples=[data_sample]
    )

    with pytest.raises(substra.exceptions.InvalidRequest):
        session.add_compute_plan(cp_spec)
```

**Expected behavior**

I should get an error.

**Comment by Kelvin-M** [comment]
@jmorel : Is it still an issue or it has been fixed ?
